// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'mobile_api.dart';
import 'mobile_node.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize the mobile database at the given path and return peer info.
Future<MobileInitStatus> initMobileDatabase({required String dbPath}) =>
    RustLib.instance.api.crateApiInitMobileDatabase(dbPath: dbPath);

/// Get current peer status (DB URL, peer ID, nickname).
Future<MobilePeerStatus> getMobilePeerStatus() =>
    RustLib.instance.api.crateApiGetMobilePeerStatus();

/// Start the p2p node: init DB, build swarm, begin listening.
Future<String> startNode({required String dbPath}) =>
    RustLib.instance.api.crateApiStartNode(dbPath: dbPath);

/// Start the p2p node with automatic DB selection (lock-based, same as TUI).
/// Scans CWD for unlocked .db files, picks the first one, or creates a new one.
Future<String> startNodeAuto() => RustLib.instance.api.crateApiStartNodeAuto();

/// Stop the p2p node.
Future<void> stopNode() => RustLib.instance.api.crateApiStopNode();

/// Get all stored TUI log messages (for Log tab display).
Future<List<String>> getLogs() => RustLib.instance.api.crateApiGetLogs();

/// Poll the next swarm event (non-blocking).
Future<SwarmEventJson?> pollEvent() => RustLib.instance.api.crateApiPollEvent();

/// Send a broadcast message.
Future<void> sendBroadcast({required String content}) =>
    RustLib.instance.api.crateApiSendBroadcast(content: content);

/// Send a direct message to a peer.
Future<void> sendDm({required String peerId, required String content}) =>
    RustLib.instance.api.crateApiSendDm(peerId: peerId, content: content);

/// Get all known peers with nicknames.
Future<List<MobilePeerRecord>> getKnownPeers() =>
    RustLib.instance.api.crateApiGetKnownPeers();

/// Load broadcast chat messages (chronological order).
Future<List<ChatMessage>> loadBroadcastMessages({
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiLoadBroadcastMessages(limit: limit);

/// Load DM history with a specific peer (chronological order).
Future<List<ChatMessage>> loadDmMessages({
  required String peerId,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiLoadDmMessages(peerId: peerId, limit: limit);

/// Save an outgoing broadcast message to DB and send via swarm.
Future<ChatMessage> saveOutgoingBroadcast({required String content}) =>
    RustLib.instance.api.crateApiSaveOutgoingBroadcast(content: content);

/// Save an outgoing DM to DB and send via swarm.
Future<ChatMessage> saveOutgoingDm({
  required String peerId,
  required String content,
}) => RustLib.instance.api.crateApiSaveOutgoingDm(
  peerId: peerId,
  content: content,
);

/// Save an incoming message (broadcast or DM) to the database.
Future<ChatMessage> saveIncomingMessage({
  required String content,
  required String peerId,
  required bool isDirect,
  String? nickname,
}) => RustLib.instance.api.crateApiSaveIncomingMessage(
  content: content,
  peerId: peerId,
  isDirect: isDirect,
  nickname: nickname,
);

/// Set the local user's nickname.
Future<void> setSelfNickname({required String nickname}) =>
    RustLib.instance.api.crateApiSetSelfNickname(nickname: nickname);
