// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'mobile_api.dart';
import 'mobile_node.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Initialize the mobile database at the given path and return peer info.
///
/// # Errors
/// Returns an error if the database cannot be opened or initialized.
Future<MobileInitStatus> initMobileDatabase({required String dbPath}) =>
    RustLib.instance.api.crateApiInitMobileDatabase(dbPath: dbPath);

/// Get current peer status (DB URL, peer ID, nickname).
///
/// # Errors
/// Returns an error if the status cannot be retrieved.
Future<MobilePeerStatus> getMobilePeerStatus() =>
    RustLib.instance.api.crateApiGetMobilePeerStatus();

/// Start the p2p node: init DB, build swarm, begin listening.
///
/// # Errors
/// Returns an error if the node fails to start.
Future<String> startNode({required String dbPath}) =>
    RustLib.instance.api.crateApiStartNode(dbPath: dbPath);

/// Start the p2p node with automatic DB selection (lock-based, same as TUI).
/// Scans CWD for unlocked .db files, picks the first one, or creates a new one.
///
/// # Errors
/// Returns an error if the node fails to start.
Future<String> startNodeAuto() => RustLib.instance.api.crateApiStartNodeAuto();

/// Stop the p2p node.
///
/// # Errors
/// Returns an error if the node fails to stop.
Future<void> stopNode() => RustLib.instance.api.crateApiStopNode();

/// Get all stored TUI log messages (for Log tab display).
Future<List<String>> getLogs() => RustLib.instance.api.crateApiGetLogs();

/// Poll the next swarm event (non-blocking).
///
/// # Errors
/// Returns an error if polling the swarm event fails.
Future<SwarmEventJson?> pollEvent() => RustLib.instance.api.crateApiPollEvent();

/// Send a broadcast message.
///
/// # Errors
/// Returns an error if the message fails to send.
Future<void> sendBroadcast({required String content}) =>
    RustLib.instance.api.crateApiSendBroadcast(content: content);

/// Send a direct message to a peer.
///
/// # Errors
/// Returns an error if the message fails to send.
Future<void> sendDm({required String peerId, required String content}) =>
    RustLib.instance.api.crateApiSendDm(peerId: peerId, content: content);

/// Get all known peers with nicknames.
///
/// This is retained as the home of the generated [`MobilePeerRecord`] Dart
/// type; Flutter's peer table prefers the single round trip
/// [`crate::mobile_api::get_peers_with_stats`].
///
/// # Errors
/// Returns an error if the peers cannot be loaded.
Future<List<MobilePeerRecord>> getKnownPeers() =>
    RustLib.instance.api.crateApiGetKnownPeers();

/// Load broadcast chat messages (chronological order).
///
/// # Errors
/// Returns an error if the messages cannot be loaded.
Future<List<ChatMessage>> loadBroadcastMessages({
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiLoadBroadcastMessages(limit: limit);

/// Load DM history with a specific peer (chronological order).
///
/// # Errors
/// Returns an error if the messages cannot be loaded.
Future<List<ChatMessage>> loadDmMessages({
  required String peerId,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiLoadDmMessages(peerId: peerId, limit: limit);

/// Save an outgoing broadcast message to DB and send via swarm.
///
/// # Errors
/// Returns an error if the message cannot be saved or sent.
Future<ChatMessage> saveOutgoingBroadcast({required String content}) =>
    RustLib.instance.api.crateApiSaveOutgoingBroadcast(content: content);

/// Save an outgoing DM to DB and send via swarm.
///
/// # Errors
/// Returns an error if the message cannot be saved or sent.
Future<ChatMessage> saveOutgoingDm({
  required String peerId,
  required String content,
}) => RustLib.instance.api.crateApiSaveOutgoingDm(
  peerId: peerId,
  content: content,
);

/// Save an incoming message (broadcast or DM) to the database.
///
/// # Errors
/// Returns an error if the message cannot be saved.
Future<ChatMessage> saveIncomingMessage({
  required String content,
  required String peerId,
  required bool isDirect,
  String? nickname,
}) => RustLib.instance.api.crateApiSaveIncomingMessage(
  content: content,
  peerId: peerId,
  isDirect: isDirect,
  nickname: nickname,
);

/// Set the local user's nickname.
///
/// # Errors
/// Returns an error if the nickname cannot be persisted.
Future<void> setSelfNickname({required String nickname}) =>
    RustLib.instance.api.crateApiSetSelfNickname(nickname: nickname);

/// Validate a nickname before persisting it.
///
/// Single source of truth shared with the desktop/TUI path
/// ([`crate::nickname::validate_nickname`]). Exposed so the Flutter UI can
/// reject invalid input without re-implementing the rules in Dart.
Future<bool> validateNickname({required String nickname}) =>
    RustLib.instance.api.crateApiValidateNickname(nickname: nickname);

/// Human-readable network-size class ("Small" / "Medium" / "Large") for a peer
/// count. Mirrors [`crate::network::NetworkSize`] so the Flutter UI doesn't
/// re-derive the thresholds in Dart.
Future<String> networkSizeLabel({required PlatformInt64 peerCount}) =>
    RustLib.instance.api.crateApiNetworkSizeLabel(peerCount: peerCount);
