// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'messages.dart';
import 'mobile_api.dart';
import 'mobile_node.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1259942970;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'p2p_app',
        ioDirectory: '../../target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<(BigInt, BigInt)> crateMobileApiCalculateVisibleRange({
    required BigInt totalMessages,
    required BigInt scrollOffset,
    required BigInt visibleCount,
  });

  String crateMobileApiFormatTimeHhmm({required String dt});

  Future<List<MobilePeerRecord>> crateApiGetKnownPeers();

  Future<List<String>> crateApiGetLogs();

  Future<MobilePeerStatus> crateApiGetMobilePeerStatus();

  Future<String> crateMobileNodeGetNodePeerId();

  Future<PeerMessageStats> crateApiGetPeerStats({required String peerId});

  Future<MobileInitStatus> crateApiInitMobileDatabase({required String dbPath});

  bool crateMobileApiIsAtBottom({
    required int scrollOffset,
    required int total,
    required int visible,
  });

  Future<List<ChatMessage>> crateApiLoadBroadcastMessages({
    required PlatformInt64 limit,
  });

  Future<List<ChatMessage>> crateApiLoadDmMessages({
    required String peerId,
    required PlatformInt64 limit,
  });

  Future<String> crateApiNetworkSizeLabel({required PlatformInt64 peerCount});

  Future<SwarmEventJson?> crateApiPollEvent();

  Future<ChatMessage> crateApiSaveIncomingMessage({
    required String content,
    required String peerId,
    required bool isDirect,
    String? nickname,
  });

  Future<ChatMessage> crateApiSaveOutgoingBroadcast({required String content});

  Future<ChatMessage> crateApiSaveOutgoingDm({
    required String peerId,
    required String content,
  });

  Future<void> crateApiSendBroadcast({required String content});

  Future<void> crateApiSendDm({
    required String peerId,
    required String content,
  });

  Future<void> crateApiSetSelfNickname({required String nickname});

  Future<String> crateApiStartNode({required String dbPath});

  Future<String> crateApiStartNodeAuto();

  Future<void> crateApiStopNode();

  Future<bool> crateApiValidateNickname({required String nickname});

  Future<bool> crateMobileApiValidateNickname({required String nick});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<(BigInt, BigInt)> crateMobileApiCalculateVisibleRange({
    required BigInt totalMessages,
    required BigInt scrollOffset,
    required BigInt visibleCount,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_usize(totalMessages, serializer);
          sse_encode_usize(scrollOffset, serializer);
          sse_encode_usize(visibleCount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_usize_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateMobileApiCalculateVisibleRangeConstMeta,
        argValues: [totalMessages, scrollOffset, visibleCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateMobileApiCalculateVisibleRangeConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_visible_range",
        argNames: ["totalMessages", "scrollOffset", "visibleCount"],
      );

  @override
  String crateMobileApiFormatTimeHhmm({required String dt}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dt, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateMobileApiFormatTimeHhmmConstMeta,
        argValues: [dt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateMobileApiFormatTimeHhmmConstMeta =>
      const TaskConstMeta(debugName: "format_time_hhmm", argNames: ["dt"]);

  @override
  Future<List<MobilePeerRecord>> crateApiGetKnownPeers() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_mobile_peer_record,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetKnownPeersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetKnownPeersConstMeta =>
      const TaskConstMeta(debugName: "get_known_peers", argNames: []);

  @override
  Future<List<String>> crateApiGetLogs() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetLogsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetLogsConstMeta =>
      const TaskConstMeta(debugName: "get_logs", argNames: []);

  @override
  Future<MobilePeerStatus> crateApiGetMobilePeerStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mobile_peer_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetMobilePeerStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetMobilePeerStatusConstMeta =>
      const TaskConstMeta(debugName: "get_mobile_peer_status", argNames: []);

  @override
  Future<String> crateMobileNodeGetNodePeerId() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateMobileNodeGetNodePeerIdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateMobileNodeGetNodePeerIdConstMeta =>
      const TaskConstMeta(debugName: "get_node_peer_id", argNames: []);

  @override
  Future<PeerMessageStats> crateApiGetPeerStats({required String peerId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_peer_message_stats,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetPeerStatsConstMeta,
        argValues: [peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetPeerStatsConstMeta =>
      const TaskConstMeta(debugName: "get_peer_stats", argNames: ["peerId"]);

  @override
  Future<MobileInitStatus> crateApiInitMobileDatabase({
    required String dbPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mobile_init_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiInitMobileDatabaseConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitMobileDatabaseConstMeta => const TaskConstMeta(
    debugName: "init_mobile_database",
    argNames: ["dbPath"],
  );

  @override
  bool crateMobileApiIsAtBottom({
    required int scrollOffset,
    required int total,
    required int visible,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_CastedPrimitive_usize(scrollOffset, serializer);
          sse_encode_CastedPrimitive_usize(total, serializer);
          sse_encode_CastedPrimitive_usize(visible, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateMobileApiIsAtBottomConstMeta,
        argValues: [scrollOffset, total, visible],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateMobileApiIsAtBottomConstMeta => const TaskConstMeta(
    debugName: "is_at_bottom",
    argNames: ["scrollOffset", "total", "visible"],
  );

  @override
  Future<List<ChatMessage>> crateApiLoadBroadcastMessages({
    required PlatformInt64 limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chat_message,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLoadBroadcastMessagesConstMeta,
        argValues: [limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoadBroadcastMessagesConstMeta =>
      const TaskConstMeta(
        debugName: "load_broadcast_messages",
        argNames: ["limit"],
      );

  @override
  Future<List<ChatMessage>> crateApiLoadDmMessages({
    required String peerId,
    required PlatformInt64 limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          sse_encode_i_64(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chat_message,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLoadDmMessagesConstMeta,
        argValues: [peerId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoadDmMessagesConstMeta => const TaskConstMeta(
    debugName: "load_dm_messages",
    argNames: ["peerId", "limit"],
  );

  @override
  Future<String> crateApiNetworkSizeLabel({required PlatformInt64 peerCount}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(peerCount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNetworkSizeLabelConstMeta,
        argValues: [peerCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkSizeLabelConstMeta => const TaskConstMeta(
    debugName: "network_size_label",
    argNames: ["peerCount"],
  );

  @override
  Future<SwarmEventJson?> crateApiPollEvent() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_swarm_event_json,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPollEventConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPollEventConstMeta =>
      const TaskConstMeta(debugName: "poll_event", argNames: []);

  @override
  Future<ChatMessage> crateApiSaveIncomingMessage({
    required String content,
    required String peerId,
    required bool isDirect,
    String? nickname,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          sse_encode_String(peerId, serializer);
          sse_encode_bool(isDirect, serializer);
          sse_encode_opt_String(nickname, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chat_message,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSaveIncomingMessageConstMeta,
        argValues: [content, peerId, isDirect, nickname],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveIncomingMessageConstMeta =>
      const TaskConstMeta(
        debugName: "save_incoming_message",
        argNames: ["content", "peerId", "isDirect", "nickname"],
      );

  @override
  Future<ChatMessage> crateApiSaveOutgoingBroadcast({required String content}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chat_message,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSaveOutgoingBroadcastConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveOutgoingBroadcastConstMeta =>
      const TaskConstMeta(
        debugName: "save_outgoing_broadcast",
        argNames: ["content"],
      );

  @override
  Future<ChatMessage> crateApiSaveOutgoingDm({
    required String peerId,
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chat_message,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSaveOutgoingDmConstMeta,
        argValues: [peerId, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveOutgoingDmConstMeta => const TaskConstMeta(
    debugName: "save_outgoing_dm",
    argNames: ["peerId", "content"],
  );

  @override
  Future<void> crateApiSendBroadcast({required String content}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSendBroadcastConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendBroadcastConstMeta =>
      const TaskConstMeta(debugName: "send_broadcast", argNames: ["content"]);

  @override
  Future<void> crateApiSendDm({
    required String peerId,
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSendDmConstMeta,
        argValues: [peerId, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendDmConstMeta => const TaskConstMeta(
    debugName: "send_dm",
    argNames: ["peerId", "content"],
  );

  @override
  Future<void> crateApiSetSelfNickname({required String nickname}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nickname, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSetSelfNicknameConstMeta,
        argValues: [nickname],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetSelfNicknameConstMeta => const TaskConstMeta(
    debugName: "set_self_nickname",
    argNames: ["nickname"],
  );

  @override
  Future<String> crateApiStartNode({required String dbPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStartNodeConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStartNodeConstMeta =>
      const TaskConstMeta(debugName: "start_node", argNames: ["dbPath"]);

  @override
  Future<String> crateApiStartNodeAuto() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStartNodeAutoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStartNodeAutoConstMeta =>
      const TaskConstMeta(debugName: "start_node_auto", argNames: []);

  @override
  Future<void> crateApiStopNode() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStopNodeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStopNodeConstMeta =>
      const TaskConstMeta(debugName: "stop_node", argNames: []);

  @override
  Future<bool> crateApiValidateNickname({required String nickname}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nickname, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiValidateNicknameConstMeta,
        argValues: [nickname],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiValidateNicknameConstMeta => const TaskConstMeta(
    debugName: "validate_nickname",
    argNames: ["nickname"],
  );

  @override
  Future<bool> crateMobileApiValidateNickname({required String nick}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nick, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateMobileApiValidateNicknameConstMeta,
        argValues: [nick],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateMobileApiValidateNicknameConstMeta =>
      const TaskConstMeta(debugName: "validate_nickname", argNames: ["nick"]);

  @protected
  int dco_decode_CastedPrimitive_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError(
      'Not implemented in this codec, please use the other one',
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  SwarmEventJson dco_decode_box_autoadd_swarm_event_json(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_swarm_event_json(raw);
  }

  @protected
  ChatMessage dco_decode_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return ChatMessage(
      id: dco_decode_i_32(arr[0]),
      content: dco_decode_String(arr[1]),
      peerId: dco_decode_opt_String(arr[2]),
      isBroadcast: dco_decode_bool(arr[3]),
      targetPeer: dco_decode_opt_String(arr[4]),
      sent: dco_decode_bool(arr[5]),
      msgId: dco_decode_opt_String(arr[6]),
      sentAt: dco_decode_opt_String(arr[7]),
      createdAt: dco_decode_String(arr[8]),
      senderNickname: dco_decode_opt_String(arr[9]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ChatMessage> dco_decode_list_chat_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chat_message).toList();
  }

  @protected
  List<MobilePeerRecord> dco_decode_list_mobile_peer_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_mobile_peer_record).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MobileInitStatus dco_decode_mobile_init_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MobileInitStatus(
      databaseUrl: dco_decode_String(arr[0]),
      localPeerId: dco_decode_String(arr[1]),
    );
  }

  @protected
  MobilePeerRecord dco_decode_mobile_peer_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return MobilePeerRecord(
      peerId: dco_decode_String(arr[0]),
      firstSeen: dco_decode_String(arr[1]),
      lastSeen: dco_decode_String(arr[2]),
      nickname: dco_decode_opt_String(arr[3]),
      localNickname: dco_decode_opt_String(arr[4]),
      displayName: dco_decode_String(arr[5]),
    );
  }

  @protected
  MobilePeerStatus dco_decode_mobile_peer_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MobilePeerStatus(
      databaseUrl: dco_decode_String(arr[0]),
      localPeerId: dco_decode_String(arr[1]),
      selfNickname: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  SwarmEventJson? dco_decode_opt_box_autoadd_swarm_event_json(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_swarm_event_json(raw);
  }

  @protected
  PeerMessageStats dco_decode_peer_message_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PeerMessageStats(
      dmCount: dco_decode_i_64(arr[0]),
      broadcastReceived: dco_decode_i_64(arr[1]),
      broadcastSent: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  (BigInt, BigInt) dco_decode_record_usize_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_usize(arr[0]), dco_decode_usize(arr[1]));
  }

  @protected
  SwarmEventJson dco_decode_swarm_event_json(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SwarmEventJson(
      eventType: dco_decode_String(arr[0]),
      peerId: dco_decode_opt_String(arr[1]),
      content: dco_decode_opt_String(arr[2]),
      latency: dco_decode_opt_String(arr[3]),
      nickname: dco_decode_opt_String(arr[4]),
      msgId: dco_decode_opt_String(arr[5]),
      address: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int sse_decode_CastedPrimitive_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_usize(deserializer);
    return inner.toInt();
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  SwarmEventJson sse_decode_box_autoadd_swarm_event_json(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_swarm_event_json(deserializer));
  }

  @protected
  ChatMessage sse_decode_chat_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_32(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_peerId = sse_decode_opt_String(deserializer);
    var var_isBroadcast = sse_decode_bool(deserializer);
    var var_targetPeer = sse_decode_opt_String(deserializer);
    var var_sent = sse_decode_bool(deserializer);
    var var_msgId = sse_decode_opt_String(deserializer);
    var var_sentAt = sse_decode_opt_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_senderNickname = sse_decode_opt_String(deserializer);
    return ChatMessage(
      id: var_id,
      content: var_content,
      peerId: var_peerId,
      isBroadcast: var_isBroadcast,
      targetPeer: var_targetPeer,
      sent: var_sent,
      msgId: var_msgId,
      sentAt: var_sentAt,
      createdAt: var_createdAt,
      senderNickname: var_senderNickname,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChatMessage> sse_decode_list_chat_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChatMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chat_message(deserializer));
    }
    return ans_;
  }

  @protected
  List<MobilePeerRecord> sse_decode_list_mobile_peer_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MobilePeerRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_mobile_peer_record(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MobileInitStatus sse_decode_mobile_init_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_databaseUrl = sse_decode_String(deserializer);
    var var_localPeerId = sse_decode_String(deserializer);
    return MobileInitStatus(
      databaseUrl: var_databaseUrl,
      localPeerId: var_localPeerId,
    );
  }

  @protected
  MobilePeerRecord sse_decode_mobile_peer_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peerId = sse_decode_String(deserializer);
    var var_firstSeen = sse_decode_String(deserializer);
    var var_lastSeen = sse_decode_String(deserializer);
    var var_nickname = sse_decode_opt_String(deserializer);
    var var_localNickname = sse_decode_opt_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    return MobilePeerRecord(
      peerId: var_peerId,
      firstSeen: var_firstSeen,
      lastSeen: var_lastSeen,
      nickname: var_nickname,
      localNickname: var_localNickname,
      displayName: var_displayName,
    );
  }

  @protected
  MobilePeerStatus sse_decode_mobile_peer_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_databaseUrl = sse_decode_String(deserializer);
    var var_localPeerId = sse_decode_String(deserializer);
    var var_selfNickname = sse_decode_opt_String(deserializer);
    return MobilePeerStatus(
      databaseUrl: var_databaseUrl,
      localPeerId: var_localPeerId,
      selfNickname: var_selfNickname,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SwarmEventJson? sse_decode_opt_box_autoadd_swarm_event_json(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_swarm_event_json(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PeerMessageStats sse_decode_peer_message_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_dmCount = sse_decode_i_64(deserializer);
    var var_broadcastReceived = sse_decode_i_64(deserializer);
    var var_broadcastSent = sse_decode_i_64(deserializer);
    return PeerMessageStats(
      dmCount: var_dmCount,
      broadcastReceived: var_broadcastReceived,
      broadcastSent: var_broadcastSent,
    );
  }

  @protected
  (BigInt, BigInt) sse_decode_record_usize_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_usize(deserializer);
    var var_field1 = sse_decode_usize(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  SwarmEventJson sse_decode_swarm_event_json(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_eventType = sse_decode_String(deserializer);
    var var_peerId = sse_decode_opt_String(deserializer);
    var var_content = sse_decode_opt_String(deserializer);
    var var_latency = sse_decode_opt_String(deserializer);
    var var_nickname = sse_decode_opt_String(deserializer);
    var var_msgId = sse_decode_opt_String(deserializer);
    var var_address = sse_decode_opt_String(deserializer);
    return SwarmEventJson(
      eventType: var_eventType,
      peerId: var_peerId,
      content: var_content,
      latency: var_latency,
      nickname: var_nickname,
      msgId: var_msgId,
      address: var_address,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_CastedPrimitive_usize(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(sseEncodeCastedPrimitiveU64(self), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_swarm_event_json(
    SwarmEventJson self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_swarm_event_json(self, serializer);
  }

  @protected
  void sse_encode_chat_message(ChatMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.id, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_opt_String(self.peerId, serializer);
    sse_encode_bool(self.isBroadcast, serializer);
    sse_encode_opt_String(self.targetPeer, serializer);
    sse_encode_bool(self.sent, serializer);
    sse_encode_opt_String(self.msgId, serializer);
    sse_encode_opt_String(self.sentAt, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_opt_String(self.senderNickname, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chat_message(
    List<ChatMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chat_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_mobile_peer_record(
    List<MobilePeerRecord> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_mobile_peer_record(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_mobile_init_status(
    MobileInitStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.databaseUrl, serializer);
    sse_encode_String(self.localPeerId, serializer);
  }

  @protected
  void sse_encode_mobile_peer_record(
    MobilePeerRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.peerId, serializer);
    sse_encode_String(self.firstSeen, serializer);
    sse_encode_String(self.lastSeen, serializer);
    sse_encode_opt_String(self.nickname, serializer);
    sse_encode_opt_String(self.localNickname, serializer);
    sse_encode_String(self.displayName, serializer);
  }

  @protected
  void sse_encode_mobile_peer_status(
    MobilePeerStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.databaseUrl, serializer);
    sse_encode_String(self.localPeerId, serializer);
    sse_encode_opt_String(self.selfNickname, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_swarm_event_json(
    SwarmEventJson? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_swarm_event_json(self, serializer);
    }
  }

  @protected
  void sse_encode_peer_message_stats(
    PeerMessageStats self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.dmCount, serializer);
    sse_encode_i_64(self.broadcastReceived, serializer);
    sse_encode_i_64(self.broadcastSent, serializer);
  }

  @protected
  void sse_encode_record_usize_usize(
    (BigInt, BigInt) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.$1, serializer);
    sse_encode_usize(self.$2, serializer);
  }

  @protected
  void sse_encode_swarm_event_json(
    SwarmEventJson self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.eventType, serializer);
    sse_encode_opt_String(self.peerId, serializer);
    sse_encode_opt_String(self.content, serializer);
    sse_encode_opt_String(self.latency, serializer);
    sse_encode_opt_String(self.nickname, serializer);
    sse_encode_opt_String(self.msgId, serializer);
    sse_encode_opt_String(self.address, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
