// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'mobile_api.dart';
import 'mobile_node.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'types.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  SwarmEventJson dco_decode_box_autoadd_swarm_event_json(dynamic raw);

  @protected
  List<PeerRecord> dco_decode_list_peer_record(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MobileInitStatus dco_decode_mobile_init_status(dynamic raw);

  @protected
  MobilePeerStatus dco_decode_mobile_peer_status(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  SwarmEventJson? dco_decode_opt_box_autoadd_swarm_event_json(dynamic raw);

  @protected
  PeerRecord dco_decode_peer_record(dynamic raw);

  @protected
  SwarmEventJson dco_decode_swarm_event_json(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  SwarmEventJson sse_decode_box_autoadd_swarm_event_json(
    SseDeserializer deserializer,
  );

  @protected
  List<PeerRecord> sse_decode_list_peer_record(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MobileInitStatus sse_decode_mobile_init_status(SseDeserializer deserializer);

  @protected
  MobilePeerStatus sse_decode_mobile_peer_status(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  SwarmEventJson? sse_decode_opt_box_autoadd_swarm_event_json(
    SseDeserializer deserializer,
  );

  @protected
  PeerRecord sse_decode_peer_record(SseDeserializer deserializer);

  @protected
  SwarmEventJson sse_decode_swarm_event_json(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_swarm_event_json(
    SwarmEventJson self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_peer_record(
    List<PeerRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mobile_init_status(
    MobileInitStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mobile_peer_status(
    MobilePeerStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_swarm_event_json(
    SwarmEventJson? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_peer_record(PeerRecord self, SseSerializer serializer);

  @protected
  void sse_encode_swarm_event_json(
    SwarmEventJson self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
