// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Per-peer message statistics shown in the peer-list table.
class PeerMessageStats {
  /// Direct messages exchanged with this peer (sent + received).
  final PlatformInt64 dmCount;

  /// Broadcast messages this peer received from us (from `broadcast_recipients`).
  final PlatformInt64 broadcastSentToPeer;

  const PeerMessageStats({
    required this.dmCount,
    required this.broadcastSentToPeer,
  });

  @override
  int get hashCode => dmCount.hashCode ^ broadcastSentToPeer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerMessageStats &&
          runtimeType == other.runtimeType &&
          dmCount == other.dmCount &&
          broadcastSentToPeer == other.broadcastSentToPeer;
}
