// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class MobileInitStatus {
  final String databaseUrl;
  final String localPeerId;

  const MobileInitStatus({
    required this.databaseUrl,
    required this.localPeerId,
  });

  @override
  int get hashCode => databaseUrl.hashCode ^ localPeerId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobileInitStatus &&
          runtimeType == other.runtimeType &&
          databaseUrl == other.databaseUrl &&
          localPeerId == other.localPeerId;
}

class MobilePeerStatus {
  final String databaseUrl;
  final String localPeerId;
  final String? selfNickname;

  const MobilePeerStatus({
    required this.databaseUrl,
    required this.localPeerId,
    this.selfNickname,
  });

  @override
  int get hashCode =>
      databaseUrl.hashCode ^ localPeerId.hashCode ^ selfNickname.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobilePeerStatus &&
          runtimeType == other.runtimeType &&
          databaseUrl == other.databaseUrl &&
          localPeerId == other.localPeerId &&
          selfNickname == other.selfNickname;
}
