// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_mobile_peer_status`, `init_mobile_database`

/// Format an ISO timestamp string ("YYYY-MM-DD HH:MM:SS") to "HH:MM".
///
/// Used by Dart/Flutter UI to display message timestamps. Uses a checked
/// character slice so a string shorter than expected never panics.
String formatTimeHhmm({required String dt}) =>
    RustLib.instance.api.crateMobileApiFormatTimeHhmm(dt: dt);

/// Check if scroll position indicates at bottom
///
/// Returns true if the scroll offset is at or past the point where the bottom
/// of the content becomes visible given the visible area size.
bool isAtBottom({
  required int scrollOffset,
  required int total,
  required int visible,
}) => RustLib.instance.api.crateMobileApiIsAtBottom(
  scrollOffset: scrollOffset,
  total: total,
  visible: visible,
);

/// Calculate first visible message index accounting for scroll
Future<(BigInt, BigInt)> calculateVisibleRange({
  required BigInt totalMessages,
  required BigInt scrollOffset,
  required BigInt visibleCount,
}) => RustLib.instance.api.crateMobileApiCalculateVisibleRange(
  totalMessages: totalMessages,
  scrollOffset: scrollOffset,
  visibleCount: visibleCount,
);

/// Validate a nickname: alphanumeric and dash only, max 20 chars.
///
/// Delegates to the canonical [`crate::nickname::validate_nickname`].
Future<bool> validateNickname({required String nick}) =>
    RustLib.instance.api.crateMobileApiValidateNickname(nick: nick);

/// Parse a `YYYY-MM-DD HH:MM:SS` (or `...T...`) timestamp into milliseconds
/// since epoch; 0 for any unparseable input.
///
/// Delegates to the canonical [`crate::fmt::parse_last_seen_ms`].
int parseLastSeenMs({required String lastSeen}) =>
    RustLib.instance.api.crateMobileApiParseLastSeenMs(lastSeen: lastSeen);

/// Sort known peers by the given column and order, mirroring the TUI peers
/// table: column `0` name, `1` DM count, `2` broadcast count, `3` last seen
/// (any other value falls back to name). Ordering always ties on `peer_id`,
/// so the result is total and stable for a given dataset.
List<PeerSortInput> sortPeers({
  required List<PeerSortInput> peers,
  required int sortColumn,
  required bool ascending,
}) => RustLib.instance.api.crateMobileApiSortPeers(
  peers: peers,
  sortColumn: sortColumn,
  ascending: ascending,
);

class MobileInitStatus {
  final String databaseUrl;
  final String localPeerId;

  const MobileInitStatus({
    required this.databaseUrl,
    required this.localPeerId,
  });

  @override
  int get hashCode => databaseUrl.hashCode ^ localPeerId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobileInitStatus &&
          runtimeType == other.runtimeType &&
          databaseUrl == other.databaseUrl &&
          localPeerId == other.localPeerId;
}

class MobilePeerStatus {
  final String databaseUrl;
  final String localPeerId;
  final String? selfNickname;

  const MobilePeerStatus({
    required this.databaseUrl,
    required this.localPeerId,
    this.selfNickname,
  });

  @override
  int get hashCode =>
      databaseUrl.hashCode ^ localPeerId.hashCode ^ selfNickname.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobilePeerStatus &&
          runtimeType == other.runtimeType &&
          databaseUrl == other.databaseUrl &&
          localPeerId == other.localPeerId &&
          selfNickname == other.selfNickname;
}

/// One row of the peers table, as fed to [`sort_peers`].
class PeerSortInput {
  final String peerId;
  final String displayName;
  final String lastSeen;
  final int dmCount;
  final int broadcastCount;

  const PeerSortInput({
    required this.peerId,
    required this.displayName,
    required this.lastSeen,
    required this.dmCount,
    required this.broadcastCount,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      displayName.hashCode ^
      lastSeen.hashCode ^
      dmCount.hashCode ^
      broadcastCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerSortInput &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          displayName == other.displayName &&
          lastSeen == other.lastSeen &&
          dmCount == other.dmCount &&
          broadcastCount == other.broadcastCount;
}
