// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SwarmEventJson {
  final String eventType;
  final String? peerId;
  final String? content;
  final String? latency;
  final String? nickname;
  final String? msgId;
  final String? address;

  const SwarmEventJson({
    required this.eventType,
    this.peerId,
    this.content,
    this.latency,
    this.nickname,
    this.msgId,
    this.address,
  });

  @override
  int get hashCode =>
      eventType.hashCode ^
      peerId.hashCode ^
      content.hashCode ^
      latency.hashCode ^
      nickname.hashCode ^
      msgId.hashCode ^
      address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwarmEventJson &&
          runtimeType == other.runtimeType &&
          eventType == other.eventType &&
          peerId == other.peerId &&
          content == other.content &&
          latency == other.latency &&
          nickname == other.nickname &&
          msgId == other.msgId &&
          address == other.address;
}
