// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ChatMessage {
  final int id;
  final String content;
  final String? peerId;
  final bool isBroadcast;
  final String? targetPeer;
  final bool sent;
  final String? msgId;
  final String? sentAt;
  final String createdAt;
  final String? senderNickname;

  const ChatMessage({
    required this.id,
    required this.content,
    this.peerId,
    required this.isBroadcast,
    this.targetPeer,
    required this.sent,
    this.msgId,
    this.sentAt,
    required this.createdAt,
    this.senderNickname,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      content.hashCode ^
      peerId.hashCode ^
      isBroadcast.hashCode ^
      targetPeer.hashCode ^
      sent.hashCode ^
      msgId.hashCode ^
      sentAt.hashCode ^
      createdAt.hashCode ^
      senderNickname.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          content == other.content &&
          peerId == other.peerId &&
          isBroadcast == other.isBroadcast &&
          targetPeer == other.targetPeer &&
          sent == other.sent &&
          msgId == other.msgId &&
          sentAt == other.sentAt &&
          createdAt == other.createdAt &&
          senderNickname == other.senderNickname;
}

class SwarmEventJson {
  final String eventType;
  final String? peerId;
  final String? content;
  final String? latency;
  final String? nickname;
  final String? msgId;
  final String? address;

  const SwarmEventJson({
    required this.eventType,
    this.peerId,
    this.content,
    this.latency,
    this.nickname,
    this.msgId,
    this.address,
  });

  @override
  int get hashCode =>
      eventType.hashCode ^
      peerId.hashCode ^
      content.hashCode ^
      latency.hashCode ^
      nickname.hashCode ^
      msgId.hashCode ^
      address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwarmEventJson &&
          runtimeType == other.runtimeType &&
          eventType == other.eventType &&
          peerId == other.peerId &&
          content == other.content &&
          latency == other.latency &&
          nickname == other.nickname &&
          msgId == other.msgId &&
          address == other.address;
}
