// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_event`, `event_to_json`, `lock_node_mutex`, `message_to_chat`, `process_event_for_mobile`, `start_node_impl`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `MobileNode`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_known_peers`, `load_broadcast_messages`, `load_dm_messages`, `poll_event`, `save_incoming_message`, `save_outgoing_broadcast`, `save_outgoing_dm`, `send_broadcast`, `send_dm`, `start_node_auto`, `start_node`, `stop_node`

/// Get the local peer ID.
///
/// # Errors
/// Returns an error if the node has not been started yet.
Future<String> getNodePeerId() =>
    RustLib.instance.api.crateMobileNodeGetNodePeerId();

class ChatMessage {
  final int id;
  final String content;
  final String? peerId;
  final bool isBroadcast;
  final String? targetPeer;
  final bool sent;
  final String? msgId;
  final String? sentAt;
  final String createdAt;
  final String? senderNickname;

  const ChatMessage({
    required this.id,
    required this.content,
    this.peerId,
    required this.isBroadcast,
    this.targetPeer,
    required this.sent,
    this.msgId,
    this.sentAt,
    required this.createdAt,
    this.senderNickname,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      content.hashCode ^
      peerId.hashCode ^
      isBroadcast.hashCode ^
      targetPeer.hashCode ^
      sent.hashCode ^
      msgId.hashCode ^
      sentAt.hashCode ^
      createdAt.hashCode ^
      senderNickname.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          content == other.content &&
          peerId == other.peerId &&
          isBroadcast == other.isBroadcast &&
          targetPeer == other.targetPeer &&
          sent == other.sent &&
          msgId == other.msgId &&
          sentAt == other.sentAt &&
          createdAt == other.createdAt &&
          senderNickname == other.senderNickname;
}

class MobilePeerRecord {
  final String peerId;
  final String firstSeen;
  final String lastSeen;
  final String? nickname;
  final String? localNickname;
  final String displayName;

  const MobilePeerRecord({
    required this.peerId,
    required this.firstSeen,
    required this.lastSeen,
    this.nickname,
    this.localNickname,
    required this.displayName,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      firstSeen.hashCode ^
      lastSeen.hashCode ^
      nickname.hashCode ^
      localNickname.hashCode ^
      displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobilePeerRecord &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          firstSeen == other.firstSeen &&
          lastSeen == other.lastSeen &&
          nickname == other.nickname &&
          localNickname == other.localNickname &&
          displayName == other.displayName;
}

class SwarmEventJson {
  final String eventType;
  final String? peerId;
  final String? content;
  final String? latency;
  final String? nickname;
  final String? msgId;
  final String? address;

  const SwarmEventJson({
    required this.eventType,
    this.peerId,
    this.content,
    this.latency,
    this.nickname,
    this.msgId,
    this.address,
  });

  @override
  int get hashCode =>
      eventType.hashCode ^
      peerId.hashCode ^
      content.hashCode ^
      latency.hashCode ^
      nickname.hashCode ^
      msgId.hashCode ^
      address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwarmEventJson &&
          runtimeType == other.runtimeType &&
          eventType == other.eventType &&
          peerId == other.peerId &&
          content == other.content &&
          latency == other.latency &&
          nickname == other.nickname &&
          msgId == other.msgId &&
          address == other.address;
}
