// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Peer record with identification and timestamps.
class PeerRecord {
  /// The peer's libp2p peer ID.
  final String peerId;

  /// Timestamp (RFC 3339) when this peer was first seen.
  final String firstSeen;

  /// Timestamp (RFC 3339) when this peer was last seen.
  final String lastSeen;

  const PeerRecord({
    required this.peerId,
    required this.firstSeen,
    required this.lastSeen,
  });

  @override
  int get hashCode => peerId.hashCode ^ firstSeen.hashCode ^ lastSeen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerRecord &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          firstSeen == other.firstSeen &&
          lastSeen == other.lastSeen;
}
