//! P2P network behavior and protocol definitions

use crate::network::NetworkSize;
use libp2p::gossipsub;
use libp2p::request_response;
use libp2p::swarm::NetworkBehaviour;
use serde::{Deserialize, Serialize};

/// Chat protocol name for direct messages
pub const DM_PROTOCOL_NAME: &str = "/p2p-chat/dm/1.0.0";

/// Default chat topic
pub const CHAT_TOPIC: &str = "test-net";

/// Direct message content with timestamp and sender info
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(default)]
pub struct DirectMessage {
    /// The message content/text
    pub content: String,
    /// Unix timestamp when the message was created
    pub timestamp: i64,
    /// Optional timestamp of when the message was sent to the network
    pub sent_at: Option<f64>,
    /// Optional nickname of the sender
    pub nickname: Option<String>,
    /// Optional unique identifier for this message
    pub msg_id: Option<String>,
    /// Optional ID of the message this is acknowledging/replying to
    pub ack_for: Option<String>,
    /// Optional timestamp of when this message was received
    pub received_at: Option<f64>,
}

/// Broadcast message content with timestamp and sender info
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(default)]
pub struct BroadcastMessage {
    /// The message content/text
    pub content: String,
    /// Optional timestamp of when the message was sent
    pub sent_at: Option<f64>,
    /// Optional nickname of the sender
    pub nickname: Option<String>,
    /// Optional unique identifier for this message
    pub msg_id: Option<String>,
}

/// JSON codec for direct message protocol
pub type ChatCodec = libp2p_request_response::json::codec::Codec<DirectMessage, DirectMessage>;

/// Combined network behavior for p2p chat
#[derive(NetworkBehaviour)]
#[allow(missing_docs)] // AppBehaviourEvent is auto-generated by the NetworkBehaviour derive macro
pub struct AppBehaviour {
    /// Gossipsub protocol handler for broadcast messages
    pub gossipsub: gossipsub::Behaviour,
    /// Request-response protocol handler for direct messages
    pub request_response: request_response::Behaviour<ChatCodec>,
    /// mDNS protocol handler for peer discovery (when mdns feature is enabled)
    #[cfg(feature = "mdns")]
    pub mdns: libp2p::mdns::tokio::Behaviour,
}

// AppBehaviourEvent is auto-generated by the NetworkBehaviour derive macro

/// Build the app behavior with appropriate protocols and configurations
///
/// # Arguments
/// * `key` - libp2p identity keypair
/// * `network_size` - Network size enum for tuning behavior parameters
pub fn build_behaviour(key: &libp2p_identity::Keypair, network_size: NetworkSize) -> AppBehaviour {
    // Configure Gossipsub based on network size
    let gossipsub_config = match network_size {
        NetworkSize::Small => {
            // 0-3 peers: aggressive message propagation
            gossipsub::ConfigBuilder::default()
                .max_transmit_size(262144)
                .history_gossip(3)
                .history_length(20)
                .heartbeat_interval(std::time::Duration::from_secs(1))
                .build()
                .expect("valid gossipsub config")
        }
        NetworkSize::Medium => {
            // 4-15 peers: balanced settings
            gossipsub::ConfigBuilder::default()
                .max_transmit_size(262144)
                .history_gossip(6)
                .history_length(30)
                .heartbeat_interval(std::time::Duration::from_secs(2))
                .build()
                .expect("valid gossipsub config")
        }
        NetworkSize::Large => {
            // 16+ peers: conservative settings
            gossipsub::ConfigBuilder::default()
                .max_transmit_size(262144)
                .history_gossip(12)
                .history_length(50)
                .heartbeat_interval(std::time::Duration::from_secs(5))
                .build()
                .expect("valid gossipsub config")
        }
    };

    let gossipsub = gossipsub::Behaviour::new(
        gossipsub::MessageAuthenticity::Signed(key.clone()),
        gossipsub_config,
    )
    .expect("valid gossipsub");

    let request_response = request_response::Behaviour::new(
        [(
            libp2p::StreamProtocol::new(DM_PROTOCOL_NAME),
            request_response::ProtocolSupport::Full,
        )],
        Default::default(),
    );

    #[cfg(feature = "mdns")]
    let mdns = libp2p::mdns::tokio::Behaviour::new(
        libp2p::mdns::Config::default(),
        libp2p::PeerId::from_public_key(&key.public()),
    )
    .expect("valid mdns");

    AppBehaviour {
        gossipsub,
        request_response,
        #[cfg(feature = "mdns")]
        mdns,
    }
}
