#![allow(missing_docs)] // covers AppBehaviourEvent generated by NetworkBehaviour derive

//! P2P network behavior and protocol definitions

use crate::network::NetworkSize;
use crate::p2plog_debug;
use libp2p::gossipsub;
use libp2p::ping;
use libp2p::request_response;
use libp2p::swarm::NetworkBehaviour;
use serde::{Deserialize, Serialize};

/// Chat protocol name for direct messages
pub const DM_PROTOCOL_NAME: &str = "/p2p-chat/dm/1.0.0";

/// Default chat topic
pub const CHAT_TOPIC: &str = "test-net";

/// Direct message content with timestamp and sender info
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(default)]
pub struct DirectMessage {
    /// The message content/text
    pub content: String,
    /// Unix timestamp when the message was created
    pub timestamp: i64,
    /// Optional timestamp of when the message was sent to the network
    pub sent_at: Option<f64>,
    /// Optional nickname of the sender
    pub nickname: Option<String>,
    /// Optional unique identifier for this message
    pub msg_id: Option<String>,
    /// Optional ID of the message this is acknowledging/replying to
    pub ack_for: Option<String>,
    /// Optional timestamp of when this message was received
    pub received_at: Option<f64>,
}

/// Broadcast message content with timestamp and sender info
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(default)]
pub struct BroadcastMessage {
    /// The message content/text
    pub content: String,
    /// Optional timestamp of when the message was sent
    pub sent_at: Option<f64>,
    /// Optional nickname of the sender
    pub nickname: Option<String>,
    /// Optional unique identifier for this message
    pub msg_id: Option<String>,
}

/// JSON codec for direct message protocol
pub type ChatCodec = libp2p_request_response::json::codec::Codec<DirectMessage, DirectMessage>;

/// Combined network behavior for p2p chat
#[derive(NetworkBehaviour)]
pub struct AppBehaviour {
    /// Gossipsub protocol handler for broadcast messages
    pub gossipsub: gossipsub::Behaviour,
    /// Request-response protocol handler for direct messages
    pub request_response: request_response::Behaviour<ChatCodec>,
    /// mDNS protocol handler for peer discovery (when mdns feature is enabled)
    #[cfg(feature = "mdns")]
    pub mdns: libp2p::mdns::tokio::Behaviour,
    /// Ping protocol for connection liveness: detects dead peers (e.g. a node
    /// that was killed without closing the connection) and closes the
    /// connection so `ConnectionClosed` fires and the peer is marked offline.
    pub ping: ping::Behaviour,
}

// AppBehaviourEvent is auto-generated by the NetworkBehaviour derive macro

/// Build the app behavior with appropriate protocols and configurations
///
/// # Arguments
/// * `key` - libp2p identity keypair
/// * `network_size` - Network size enum for tuning behavior parameters
///
/// # Errors
/// Returns an error if any underlying libp2p protocol behavior fails to build
/// (e.g. an invalid gossipsub configuration or mDNS setup).
pub fn build_behaviour(
    key: &libp2p_identity::Keypair,
    network_size: NetworkSize,
) -> Result<AppBehaviour, String> {
    p2plog_debug(format!(
        "Building behavior for network size: {network_size:?}"
    ));
    // Configure Gossipsub based on network size: larger networks need a longer
    // history and a slower heartbeat to avoid redundant re-broadcasts.
    let (history_gossip, history_length, heartbeat_secs) = match network_size {
        NetworkSize::Small => (3, 20, 1),
        NetworkSize::Medium => (6, 30, 2),
        NetworkSize::Large => (12, 50, 5),
    };
    let gossipsub_config = gossipsub::ConfigBuilder::default()
        .max_transmit_size(262_144)
        .history_gossip(history_gossip)
        .history_length(history_length)
        .heartbeat_interval(std::time::Duration::from_secs(heartbeat_secs))
        .build()
        .map_err(|e| format!("invalid gossipsub config: {e}"))?;

    let gossipsub = gossipsub::Behaviour::new(
        gossipsub::MessageAuthenticity::Signed(key.clone()),
        gossipsub_config,
    )
    .map_err(|e| format!("Failed to create gossipsub behavior: {e}"))?;

    let request_response = request_response::Behaviour::new(
        [(
            libp2p::StreamProtocol::new(DM_PROTOCOL_NAME),
            request_response::ProtocolSupport::Full,
        )],
        request_response::Config::default(),
    );

    // Liveness checks: ping every 10s, treat a missing pong within 10s as a
    // dead connection. This surfaces killed/disconnected peers within ~10-20s
    // instead of waiting on the (often never-elapsed) idle connection timeout.
    let ping = ping::Behaviour::new(
        ping::Config::new()
            .with_interval(std::time::Duration::from_secs(10))
            .with_timeout(std::time::Duration::from_secs(10)),
    );

    #[cfg(feature = "mdns")]
    let mdns = libp2p::mdns::tokio::Behaviour::new(
        libp2p::mdns::Config::default(),
        libp2p::PeerId::from_public_key(&key.public()),
    )
    .map_err(|e| format!("invalid mdns: {e}"))?;

    Ok(AppBehaviour {
        gossipsub,
        request_response,
        #[cfg(feature = "mdns")]
        mdns,
        ping,
    })
}

/// Build a fully configured libp2p swarm for chat.
///
/// Sets up TCP (with nodelay), optional QUIC transport, the app behaviour
/// with adaptive network size, and a 60-second idle connection timeout.
///
/// # Errors
/// Returns an error if the libp2p identity cannot be loaded or if the swarm
/// (transport + behaviour) fails to build.
pub fn build_swarm(
    network_size: NetworkSize,
) -> color_eyre::Result<libp2p::swarm::Swarm<AppBehaviour>> {
    use std::time::Duration;

    let key = crate::get_libp2p_identity()?;

    let base = libp2p::SwarmBuilder::with_existing_identity(key)
        .with_tokio()
        .with_tcp(
            libp2p::tcp::Config::default().nodelay(true),
            libp2p::noise::Config::new,
            libp2p::yamux::Config::default,
        )?;

    #[cfg(feature = "quic")]
    let base = base.with_quic();

    let swarm = base
        .with_behaviour(
            |key| -> Result<AppBehaviour, Box<dyn std::error::Error + Send + Sync>> {
                build_behaviour(key, network_size).map_err(
                    |e| -> Box<dyn std::error::Error + Send + Sync> {
                        Box::new(std::io::Error::other(e))
                    },
                )
            },
        )?
        .with_swarm_config(|c| c.with_idle_connection_timeout(Duration::from_mins(1)))
        .build();

    Ok(swarm)
}

#[cfg(test)]
#[path = "../tests/unit/unit_behavior.rs"]
mod tests;
