// Generated by Diesel (queryable structs)

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::*;
use chrono::NaiveDateTime;
use diesel::{Queryable, Selectable};

#[derive(Queryable, Selectable, Debug, Clone)]
#[diesel(table_name = identities)]
pub struct Identity {
    pub id: i32,
    pub created_at: NaiveDateTime,
    pub key: Vec<u8>,
    pub last_tcp_port: Option<i32>,
    pub last_quic_port: Option<i32>,
    pub self_nickname: Option<String>,
}

#[derive(Queryable, Selectable, Debug, Clone)]
#[diesel(table_name = messages)]
pub struct Message {
    pub id: i32,
    pub created_at: NaiveDateTime,
    pub content: String,
    pub peer_id: Option<String>,
    pub topic: String,
    pub sent: i32,
    pub is_direct: i32,
    pub target_peer: Option<String>,
}

#[derive(Queryable, Selectable, Debug, Clone)]
#[diesel(table_name = peer_sessions)]
pub struct PeerSession {
    pub id: i32,
    pub concurrent_peers: i32,
    pub recorded_at: NaiveDateTime,
}

#[derive(Queryable, Selectable, Debug, Clone)]
#[diesel(table_name = peers)]
pub struct Peer {
    pub id: i32,
    pub created_at: NaiveDateTime,
    pub peer_id: String,
    pub addresses: String,
    pub first_seen: NaiveDateTime,
    pub last_seen: NaiveDateTime,
    pub peer_local_nickname: Option<String>,
    pub received_nickname: Option<String>,
}
