// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::*;

use chrono::NaiveDateTime;
use diesel::prelude::*;
#[derive(Queryable, Selectable, Debug)]
#[diesel(table_name = identities)]
pub struct Identity {
    pub id: i32,
    pub created_at: NaiveDateTime,
    pub key: Vec<u8>,
}

#[derive(Queryable, Selectable, Debug)]
#[diesel(table_name = messages)]
pub struct Message {
    pub id: i32,
    pub created_at: NaiveDateTime,
    pub content: String,
    pub peer_id: Option<String>,
    pub topic: String,
    pub sent: i32,
    pub is_direct: i32,
    pub target_peer: Option<String>,
}

#[derive(Queryable, Selectable, Debug)]
#[diesel(table_name = peers)]
pub struct Peer {
    pub id: i32,
    pub created_at: NaiveDateTime,
    pub peer_id: String,
    pub addresses: String,
    pub last_seen: NaiveDateTime,
}
