// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::*;

use chrono::NaiveDateTime;
use diesel::prelude::*;

#[derive(Queryable, Selectable, Debug, Clone)]
#[diesel(table_name = identities)]
pub struct Identity {
    pub id: i32,
    pub created_at: NaiveDateTime,
    pub key: Vec<u8>,
    pub last_tcp_port: Option<i32>,
    pub last_quic_port: Option<i32>,
    pub self_nickname: Option<String>,
}

impl Identity {
    #[must_use]
    pub fn last_port(&self) -> Option<i32> {
        self.last_tcp_port.or(self.last_quic_port)
    }
}

#[derive(Queryable, Selectable, Debug, Clone)]
#[diesel(table_name = messages)]
pub struct Message {
    pub id: i32,
    pub created_at: NaiveDateTime,
    pub content: String,
    pub peer_id: Option<String>,
    pub topic: String,
    pub sent: i32,
    pub is_direct: i32,
    pub target_peer: Option<String>,
}

impl Message {
    #[must_use]
    pub fn is_sent(&self) -> bool {
        self.sent != 0
    }

    #[must_use]
    pub fn is_broadcast(&self) -> bool {
        self.is_direct == 0
    }

    #[must_use]
    pub fn is_direct_message(&self) -> bool {
        self.is_direct != 0
    }

    #[must_use]
    pub fn is_from_local_user(&self) -> bool {
        self.peer_id.is_none()
    }
}

#[derive(Queryable, Selectable, Debug, Clone)]
#[diesel(table_name = peer_sessions)]
pub struct PeerSession {
    pub id: i32,
    pub concurrent_peers: i32,
    pub recorded_at: NaiveDateTime,
}

impl PeerSession {
    #[must_use]
    pub fn peer_count(&self) -> usize {
        self.concurrent_peers.unsigned_abs() as usize
    }
}

#[derive(Queryable, Selectable, Debug, Clone)]
#[diesel(table_name = peers)]
pub struct Peer {
    pub id: i32,
    pub created_at: NaiveDateTime,
    pub peer_id: String,
    pub addresses: String,
    pub first_seen: NaiveDateTime,
    pub last_seen: NaiveDateTime,
    pub peer_local_nickname: Option<String>,
    pub received_nickname: Option<String>,
}

impl Peer {
    #[must_use]
    pub fn display_name(&self) -> String {
        self.peer_local_nickname
            .clone()
            .or_else(|| self.received_nickname.clone())
            .unwrap_or_else(|| {
                self.peer_id
                    .chars()
                    .rev()
                    .take(8)
                    .collect::<String>()
                    .chars()
                    .rev()
                    .collect()
            })
    }

    #[must_use]
    pub fn address_list(&self) -> Vec<String> {
        self.addresses
            .split(',')
            .map(ToString::to_string)
            .filter(|s| !s.is_empty())
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn create_test_message(sent: i32, is_direct: i32, peer_id: Option<&str>) -> Message {
        Message {
            id: 1,
            created_at: chrono::NaiveDateTime::from_timestamp_opt(0, 0).unwrap(),
            content: "test".to_string(),
            peer_id: peer_id.map(String::from),
            topic: "test".to_string(),
            sent,
            is_direct,
            target_peer: None,
        }
    }

    #[test]
    fn test_message_is_sent() {
        assert!(create_test_message(1, 0, None).is_sent());
        assert!(!create_test_message(0, 0, None).is_sent());
    }

    #[test]
    fn test_message_is_broadcast() {
        assert!(create_test_message(0, 0, None).is_broadcast());
        assert!(!create_test_message(0, 1, None).is_broadcast());
    }

    #[test]
    fn test_message_is_direct_message() {
        assert!(create_test_message(0, 1, None).is_direct_message());
        assert!(!create_test_message(0, 0, None).is_direct_message());
    }

    #[test]
    fn test_message_is_from_local_user() {
        assert!(create_test_message(0, 0, None).is_from_local_user());
        assert!(!create_test_message(0, 0, Some("peer1")).is_from_local_user());
    }

    fn create_test_peer(
        peer_local_nickname: Option<&str>,
        received_nickname: Option<&str>,
    ) -> Peer {
        Peer {
            id: 1,
            created_at: chrono::NaiveDateTime::from_timestamp_opt(0, 0).unwrap(),
            peer_id: "12D3KooWTestPeerIdABCDEFGH".to_string(),
            addresses: "/ip4/127.0.0.1/tcp/1234".to_string(),
            first_seen: chrono::NaiveDateTime::from_timestamp_opt(0, 0).unwrap(),
            last_seen: chrono::NaiveDateTime::from_timestamp_opt(0, 0).unwrap(),
            peer_local_nickname: peer_local_nickname.map(String::from),
            received_nickname: received_nickname.map(String::from),
        }
    }

    #[test]
    fn test_peer_display_name_local_nickname() {
        let peer = create_test_peer(Some("Alice"), Some("Bob"));
        assert_eq!(peer.display_name(), "Alice");
    }

    #[test]
    fn test_peer_display_name_received_nickname() {
        let peer = create_test_peer(None, Some("Charlie"));
        assert_eq!(peer.display_name(), "Charlie");
    }

    #[test]
    fn test_peer_display_name_fallback() {
        let peer = create_test_peer(None, None);
        assert_eq!(peer.display_name().len(), 8);
    }

    #[test]
    fn test_peer_address_list() {
        let peer = Peer {
            id: 1,
            created_at: chrono::NaiveDateTime::from_timestamp_opt(0, 0).unwrap(),
            peer_id: "12D3KooWTest".to_string(),
            addresses: "/ip4/127.0.0.1/tcp/1234,/ip4/192.168.1.1/tcp/5678,".to_string(),
            first_seen: chrono::NaiveDateTime::from_timestamp_opt(0, 0).unwrap(),
            last_seen: chrono::NaiveDateTime::from_timestamp_opt(0, 0).unwrap(),
            peer_local_nickname: None,
            received_nickname: None,
        };
        let addrs = peer.address_list();
        assert_eq!(addrs.len(), 2);
        assert_eq!(addrs[0], "/ip4/127.0.0.1/tcp/1234");
        assert_eq!(addrs[1], "/ip4/192.168.1.1/tcp/5678");
    }

    #[test]
    fn test_peer_address_list_empty() {
        let peer = Peer {
            id: 1,
            created_at: chrono::NaiveDateTime::from_timestamp_opt(0, 0).unwrap(),
            peer_id: "12D3KooWTest".to_string(),
            addresses: String::new(),
            first_seen: chrono::NaiveDateTime::from_timestamp_opt(0, 0).unwrap(),
            last_seen: chrono::NaiveDateTime::from_timestamp_opt(0, 0).unwrap(),
            peer_local_nickname: None,
            received_nickname: None,
        };
        assert!(peer.address_list().is_empty());
    }

    fn create_test_identity(last_tcp: Option<i32>, last_quic: Option<i32>) -> Identity {
        Identity {
            id: 1,
            created_at: chrono::NaiveDateTime::from_timestamp_opt(0, 0).unwrap(),
            key: vec![],
            last_tcp_port: last_tcp,
            last_quic_port: last_quic,
            self_nickname: None,
        }
    }

    #[test]
    fn test_identity_last_port_tcp() {
        let identity = create_test_identity(Some(8080), None);
        assert_eq!(identity.last_port(), Some(8080));
    }

    #[test]
    fn test_identity_last_port_quic() {
        let identity = create_test_identity(None, Some(9090));
        assert_eq!(identity.last_port(), Some(9090));
    }

    #[test]
    fn test_identity_last_port_both() {
        let identity = create_test_identity(Some(8080), Some(9090));
        assert_eq!(identity.last_port(), Some(8080));
    }

    #[test]
    fn test_identity_last_port_none() {
        let identity = create_test_identity(None, None);
        assert_eq!(identity.last_port(), None);
    }

    #[test]
    fn test_peer_session_peer_count() {
        let session = PeerSession {
            id: 1,
            concurrent_peers: 5,
            recorded_at: chrono::NaiveDateTime::from_timestamp_opt(0, 0).unwrap(),
        };
        assert_eq!(session.peer_count(), 5);
    }
}
