// Generated by diesel_ext (insertable structs)

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::*;
use diesel::Insertable;

use chrono::NaiveDateTime;

#[derive(Insertable, Debug)]
#[diesel(table_name = identities)]
pub struct NewIdentity {
    pub key: Vec<u8>,
    pub last_tcp_port: Option<i32>,
    pub last_quic_port: Option<i32>,
    pub self_nickname: Option<String>,
}

impl NewIdentity {
    pub fn new(key: Vec<u8>) -> Self {
        Self {
            key,
            last_tcp_port: None,
            last_quic_port: None,
            self_nickname: None,
        }
    }
}

#[derive(Insertable, Debug)]
#[diesel(table_name = messages)]
pub struct NewMessage {
    pub content: String,
    pub peer_id: Option<String>,
    pub topic: String,
    pub sent: i32,
    pub is_direct: i32,
    pub target_peer: Option<String>,
}

impl NewMessage {
    pub fn broadcast(content: String, topic: &str) -> Self {
        Self {
            content,
            peer_id: None,
            topic: topic.to_string(),
            sent: 0,
            is_direct: 0,
            target_peer: None,
        }
    }

    pub fn direct(content: String, topic: &str, target_peer: &str) -> Self {
        Self {
            content,
            peer_id: None,
            topic: topic.to_string(),
            sent: 0,
            is_direct: 1,
            target_peer: Some(target_peer.to_string()),
        }
    }
}

#[derive(Insertable, Debug)]
#[diesel(table_name = peer_sessions)]
pub struct NewPeerSession {
    pub concurrent_peers: i32,
    pub recorded_at: NaiveDateTime,
}

impl NewPeerSession {
    pub fn new(concurrent_peers: i32) -> Self {
        Self {
            concurrent_peers,
            recorded_at: chrono::Utc::now().naive_utc(),
        }
    }
}

#[derive(Insertable, Debug)]
#[diesel(table_name = peers)]
pub struct NewPeer {
    pub peer_id: String,
    pub addresses: String,
    pub first_seen: NaiveDateTime,
    pub last_seen: NaiveDateTime,
    pub peer_local_nickname: Option<String>,
    pub received_nickname: Option<String>,
}

impl NewPeer {
    pub fn new(peer_id: String, addresses: Vec<String>) -> Self {
        let now = chrono::Utc::now().naive_utc();
        Self {
            peer_id,
            addresses: addresses.join(","),
            first_seen: now,
            last_seen: now,
            peer_local_nickname: None,
            received_nickname: None,
        }
    }

    pub fn with_nickname(mut self, nickname: String) -> Self {
        self.peer_local_nickname = Some(nickname);
        self
    }
}
