// Generated by diesel_ext (insertable structs)

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::*;
use diesel::Insertable;

#[derive(Debug, Insertable)]
#[diesel(table_name = identities)]
pub struct NewIdentity {
    pub key: Vec<u8>,
}

#[derive(Debug, Insertable)]
#[diesel(table_name = messages)]
pub struct NewMessage<'a> {
    pub content: &'a str,
    pub peer_id: Option<&'a str>,
    pub topic: &'a str,
    pub sent: i32,
}
